services:
  # --------------------
  # Redis (queue + cache)
  # --------------------
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # --------------------
  # Neo4j
  # --------------------
  neo4j:
    image: neo4j:2025.11.2
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/rabbithole
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

  # --------------------
  # Flask API
  # --------------------
  web:
    build: .
    command: python run.py
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    environment:
      # Flask
      FLASK_ENV: development
      PORT: 5000

      # Celery
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      REDIS_HOST: redis

      # Neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: rabbithole
    depends_on:
      - redis
      - neo4j

  # --------------------
  # Celery Worker
  # --------------------
  worker:
    build: .
    command: celery -A app.celery_app:celery_app worker --pool=solo --loglevel=INFO -E
    volumes:
      - .:/usr/src/app
    environment:
      # Celery
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
      REDIS_HOST: redis

      # Neo4j
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: rabbithole
    depends_on:
      - redis
      - web

volumes:
  neo4j_data:
